### ISSUE TITLE
Go SDK build errors on worktree not clean in GHA

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-scaleway#105]
@jaxxstorm the build of the Go SDK for this provider errors that the worktree is not clean when building on Github Actions:

https://github.com/pulumiverse/pulumi-scaleway/runs/7856771524?check_suite_focus=true

After running `make build_sdks` on my local system, my worktree is clean. I can't reproduce this error. I [cleaned my Go module cache](https://lecstor.com/go-clear-cache/) and retried but still can't reproduce this.

Do you have any idea on how to fix this?

**Comment by jaxxstorm** [comment]
It looks like the Go version isn't pinned, so it's pulling Go version 1.19:

https://github.com/pulumiverse/pulumi-scaleway/blob/master/.github/workflows/main.yml#L39

We need to pin the Go version or update our local one
