### ISSUE TITLE
PyPi publishing is failing

### ISSUE THREAD

**Issue by jaxxstorm** [pulumiverse/pulumi-scaleway#113]
It seems like the password defined for PyPi isn't correct:

`PYPI_API_TOKEN` is how it's set in the secrets, is that correct? @ringods

**Comment by ringods** [comment]
@jaxxstorm indeed. I have regenerated the token on pypi.org and updated the Github Actions secret in this repo. Can you retry?

**Comment by ringods** [comment]
@jaxxstorm could you update this line? It's reading the wrong GHA secret:

https://github.com/pulumiverse/pulumi-scaleway/blob/58d40833ed986e78de6f7ce4dcad692cecb55588/.github/workflows/release.yml#L14

**Comment by jaxxstorm** [comment]
Resolved now we have the correct tokens
