### ISSUE TITLE
Official Java package or source generation instructions

### ISSUE THREAD

**Issue by apankowski** [pulumiverse/pulumi-scaleway#129]
I'm trying to test Pulumi with Scaleway and Kotlin. I thought that I should be able to use this provider since Kotlin has good interop with Java.

In the Pulumi registry [the Scaleway provider](https://www.pulumi.com/registry/packages/scaleway/) doesn't seem to show a simple Java example. [Installation & configuration examples](https://www.pulumi.com/registry/packages/scaleway/installation-configuration/) don't seem to mention Java either.
 
However, for individual resources I see Java snippets ([example here](https://www.pulumi.com/registry/packages/scaleway/api-docs/database/)) referencing `com.pulumi.scaleway` package. I also see `build_java` target in the [Makefile](https://github.com/lbrlabs/pulumi-scaleway/blob/master/Makefile#L73). But I was unable to find the Scaleway provider artifact in the official Maven repository under such package.

Since I'm new to Pulumi and the Scaleway provider, is Java actually supported by the Scaleway provider? If so, what's the simplest way of obtaining the Java artifact or generating sources for it?

**Comment by jaxxstorm** [comment]
hi @apankowski - I don't currently support the Java SDK, I'll leave this open until it's published to maven

**Comment by ringods** [comment]
Ownership of this provider has been transferred to `pulumiverse`. We are tracking this for all providers in this organization globally here:

https://github.com/pulumiverse/infra/issues/44
