### ISSUE TITLE
Failed to install scaleway plugin

### ISSUE THREAD

**Issue by Finkes** [pulumiverse/pulumi-scaleway#161]
I was trying to follow the [installation & configuration instructions](https://www.pulumi.com/registry/packages/scaleway/installation-configuration/) section from the pulumi docs when I ran into multiple issues: 

When running `pulumi up` the following error occurred:

Previewing update (preview):
```
     Type                          Name                                    Plan        Info
     pulumi:pulumi:Stack           my-infra-preview                    running..   
     └─ pulumi:providers:scaleway  default_github_/api.github.com/lbrlabs              error: Could not automatically download and install resource plugin 'pulumi-resource-scaleway', install the plugin using `pulumi plugin install resource scaleway`.
```

> error: Could not automatically download and install resource plugin 'pulumi-resource-scaleway', install the plugin using `pulumi plugin install resource scaleway`.

Diagnostics:
```
  pulumi:providers:scaleway (default_github_/api.github.com/lbrlabs):
    error: Could not automatically download and install resource plugin 'pulumi-resource-scaleway', install the plugin using `pulumi plugin install resource scaleway`.
    Underlying error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-scaleway/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

When I try to run the suggested installation command, I receive another error:

```
pulumi plugin install resource scaleway

404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-scaleway/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```
I'm wondering why the url is pointing to `pulumi/pulumi-scaleway` instead of `lbrlabs/pulumi-scaleway`?

When I try to install a specific version, I receive yet another error:

```
 pulumi plugin install resource scaleway v1.3.0

[resource plugin scaleway-1.3.0] installing
error: [resource plugin scaleway-1.3.0] downloading from : failed to download plugin: scaleway-1.3.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-scaleway-v1.3.0-darwin-arm64.tar.gz
```

**Workaround**
1. Download the release manually from the GitHub Release section
2. Install the plugin from the tarball: `pulumi plugin install -f ~/Downloads/pulumi-resource-scaleway-v1.3.0-darwin-arm64.tar.gz resource scaleway v1.3.0`

**Context**
pulumi cli version: v3.46.0
language: Go (1.19)
architecture: Darwin ARM64 (Mac M1 Pro)

**Comment by jaxxstorm** [comment]
The issue here appears to be the error generated. The correct install command is

```
pulumi plugin install resource scaleway --server github://api.github.com/lbrlabs
```
