### ISSUE TITLE
Go: Unable to get version v1.9.0 of the sdk module

### ISSUE THREAD

**Issue by 0x1DA117** [pulumiverse/pulumi-scaleway#245]
I'm not quite sure whether this is an issue with this project, my Go setup or Go itself, but I already searched for the issue on the internet and Gopher Slack as well and I couldn't find an answer.

I started a fresh new project, imported the module in my main.go file and when I ran `go mod tidy`, it downloaded v1.8.0. Unfortunately there is a new feature in v1.9.0 that I need. So I tried updating, but nothing seems to work.

This is the error I get:

```
go mod download github.com/lbrlabs/pulumi-scaleway/sdk@v1.9.0
go: github.com/lbrlabs/pulumi-scaleway/sdk@v1.9.0: invalid version: unknown revision sdk/v1.9.0
```

Specifying `latest` instead of `v1.9.0` will download v1.8.0.

**Comment by 0x1DA117** [comment]
I was able to use the commit hash as revision.
So this worked somehow:

```
go mod download github.com/lbrlabs/pulumi-scaleway/sdk@ca8df6a6bd0fa9f2c3600d5ef8a0f44c0fb139a8
```

**Comment by 0x1DA117** [comment]
Also... I installed the resource plugin version v1.9.0 manually.
Now when I run `pulumi preview` it automatically installs version v1.8.0

I'm confused now.

**Comment by 0x1DA117** [comment]
This issue still applies to version 1.10.0

```
% go mod download github.com/lbrlabs/pulumi-scaleway/sdk@v1.10.0
go: github.com/lbrlabs/pulumi-scaleway/sdk@v1.10.0: invalid version: unknown revision sdk/v1.10.0
```

**Comment by ringods** [comment]
@0x1DA117 can you retry with version `sdk/v1.12.0` or `sdk/v1.12.1` and report back if you have succes with one of these versions?

**Comment by 0x1DA117** [comment]
Both worked. Thanks.
