### ISSUE TITLE
1.11.0 tags point to non-existing commits

### ISSUE THREAD

**Issue by andrzejressel** [pulumiverse/pulumi-scaleway#261]
![image](https://github.com/lbrlabs/pulumi-scaleway/assets/1307829/ca781ed1-f751-492a-b990-a88e00af472c)

It breaks git when pulling forked repository

**Comment by ringods** [comment]
@andrzejressel can you test with v1.11.1?

Keep in mind that the owner of this provider changed and you need to migrate your code to use the new package names:

https://www.pulumi.com/registry/packages/scaleway/installation-configuration/#migrating-from-the-lbrlabs-package

**Comment by andrzejressel** [comment]
I believe it's working fine now.
