### ISSUE TITLE
Upgrade of the terraform scaleway provider seems broken without easy fix

### ISSUE THREAD

**Issue by mtparet** [pulumiverse/pulumi-scaleway#295]
cf broken PR https://github.com/pulumiverse/pulumi-scaleway/pull/293 and issue
https://github.com/scaleway/terraform-provider-scaleway/issues/2597

**Comment by ringods** [comment]
Scaleway TF provider v2.40.0 -> Pulumi provider v1.13.0
Scaleway TF provider v2.41.1 -> Pulumi provider v1.14.0

Publishing the accompanying docs happens twice a day. The docs for the latest release should be picked up end of day CET.

**Comment by mtparet** [comment]
Thanks a lot! I will try proposing next update PR when there are new Terraform Scaleway provider.

**Comment by ringods** [comment]
@mtparet no need to do that. We have an automated tool to do that named [upgrade-provider](https://github.com/pulumi/upgrade-provider/). Here is an GHA workflow which triggers that:

https://github.com/pulumiverse/pulumi-scaleway/blob/main/.github/workflows/upgrade-provider.yml

**Comment by mtparet** [comment]
ooh great, once a week should be enough :)

**Comment by ringods** [comment]
@mtparet I checked this morning and the docs for version 1.14 were not yet listed, so I went digging. There was a recent change to the tooling behind the publishing of the API docs which generated the files in the wrong place. I filed an issue internally to have this fixed.

So expect a delay in the correct docs to appear. 🙏🏻
